### ISSUE TITLE
Does not work with Docker containers

### ISSUE THREAD

**Issue by solvingj** [PlagueHO/SystemLocaleDsc#22]
I was hopeful that this would somehow allow us to set the SystemLocale in a docker container.  Sadly, it does not seem to work, presumably for whatever mysterious reason running the relevant powershell commands directly doesn't work. 

To reproduce, here is a "Dockerfile" you can build with command: 

`docker build . -t systemlocaledsc-test`

```
# escape=`

FROM mcr.microsoft.com/windows:1809

RUN Install-PackageProvider -Name NuGet -Force

RUN Install-Module 'PSDscResources' -Force

RUN Install-Module -Name SystemLocaleDsc -Force

COPY setsystemlocale.ps1 C:\CarSim\setsystemlocale.ps1

RUN powershell.exe C:\CarSim\setsystemlocale.ps1

RUN Get-WinSystemLocale
```

**Comment by PlagueHO** [comment]
Hi @solvingj - this module has actually been deprecated and the resource rolled into ComputerManagementDsc, but due to an oversight I hadn't updated the README.MD on this page to indicate this.

The resource is the same though, so I suspect the same problem will still occur. 

Can you:
1. Change your config to use the ComputerManagementDsc module and raise this issue over there (https://github.com/dsccommunity/ComputerManagementDsc/issues) if it still occurs?
1. Can you get the Verbose logs of applying the DSC config and paste them in the issue? That will give us a better idea of what is failing when setting the System Locale.

Although DSC should be quite capable of running in a container, it loses some of the value because containers are usually stateless and config drift is managed by simply restarting the container. Is there some specific behaviour of DSC that you need in the container or is it possible to just use plain PowerShell code to set the System Locale? E.g.

```powershell
Set-WinSystemLocale -SystemLocale 'en-US'
```

**Comment by solvingj** [comment]
no, was just hoping that this dsc module was doing some magic under the hood that normal powershell commands wasn't doing, and/or that that there was an interest in making sure this module could work in a container, and/or that someone involved with this project might know a powershell mechanism that could help me workaround the issue.  In truth, this really isn't a problem of this module at all.
